name: Executar um script python que lê parâmetros.

on:
  # permite rodar manualmente e mostrar o formulário de inputs
  workflow_dispatch:
    inputs:
      Ambiente:
        description: "Escolha o Environment"
        type: environment     # mostra dropdown dos environments (ex.: STAGING)
        required: true
      Nome:
        description: "Nome próprio"
        default: "Vieira"
        required: true
      Apelido:
        description: "Apelido / Sobrenome"
        default: "Danho"
        required: true
      Confirme:
        description: "Confirmar execução?"
        type: boolean
        default: true
      Cidade:
        description: "Cidade"
        type: choice
        options:
          - Lisboa
          - Braga
          - Porto
          - Coimbra
        default: Lisboa

jobs:
  build:
    # vincula o job ao Environment selecionado no formulário
    environment: ${{ inputs.Ambiente }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Echo inputs (debug)
        run: |
          echo "Ambiente = ${{ inputs.Ambiente }}"
          echo "Nome     = ${{ inputs.Nome }}"
          echo "Apelido  = ${{ inputs.Apelido }}"
          echo "Confirme  = ${{ inputs.Confirme }}"
          echo "Cidade   = ${{ inputs.Cidade }}"

      - name: Run exemplo.py with inputs
        env:
          # útil se quiser ler no script via os.getenv
          GITHUB_ENVIRONMENT: ${{ inputs.Ambiente }}
        run: |
          python exemplo.py "${{ inputs.Nome }}" "${{ inputs.Apelido }}" "${{ inputs.Confirme }}" "${{ inputs.Cidade }}"
